### PR TITLE
fix command formatting

### PR DESCRIPTION
**Pull request by cheikhshift**

### CODE REVIEW

**Comment by orbitturner** [comment]
Hello Cheikh 👋🏾

I have seen your PR but I'm not getting it.
Is it just about deleting & adding trailing spaces ?

**Comment by cheikhshift** [comment]
Adding spaces before the command to tell markdown it is a code block. Also great doc but there's too much going on there. No one will take a document with emojis seriously

**Comment by orbitturner** [comment]
Oh ok i get it 🙏🏾
But for the emojis and fancy stuffs its part of my theme and design mood 😅 All of my Readme's are like that so it will not change in the future 😁

**Comment by cheikhshift** [comment]
Fair enough. Keep up the good work!

**Pull request merged**
